version: "3.0"

expectations:
  population_size: 100000

actions:

# PRIMARY ANALYSES 
    
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition 
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  00_data_management:
    run: stata-mp:latest analysis/00_data_management.do output/input.csv tempdata/temp_data
    needs: [generate_cohort] 
    outputs:
      moderately_sensitive: 
        log: output/logs/00_data_management.log 
